eloqua_api_auth_fallback.settings:
  type: config_object
  label: 'Eloqua API Authentication settings'
  mapping:
    sitename:
      type: string
      label: 'Site/Company Name'
    username:
      type: string
      label: 'Username'
    password:
      type: string
      label: 'Password'
